sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: selflearningonline
    username: root
    password: G.E.M0816
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tNUAzR62gSz11ERNUXn
    access-key-secret: ASad0UBQTOcEbQEKHtBjRjzjyxQ5ME
    bucket-name: gemxhq-bucket
